import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./componets/Footer";
import Navs from "./componets/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navs/> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
